### ISSUE TITLE
feat: Create login form so user could login to our backend

### ISSUE THREAD

**Issue by annabauza** [anitab-org/stem-diverse-tv-cms#10]
### Is your feature request related to a problem? Please describe.
As a user I want to fill login form  so I could login into our [backend](https://stem-diverse-tv.herokuapp.com/).

### Describe the solution you'd like
Login form design can be find [here](https://www.figma.com/file/klxnTZJ8Z2uAtxHS1CRTWO/Untitled?node-id=3%3A1)
![Login](https://user-images.githubusercontent.com/31966073/106380387-c7582e80-63a9-11eb-9e79-efccda04e994.png)

### Additional context
After login user should be redirect to empty home page.

**Comment by vatsalkul** [comment]
Can i take this issue @annabauza

**Comment by annabauza** [comment]
yours!

**Comment by annabauza** [comment]
how it's going @vatsalkul ?

**Comment by vatsalkul** [comment]
@annabauza I am making myself familiar with TypeScript and React. These are kind of new tech stack for me. If you want you can take this issue and I can learn react in the meantime.

**Comment by annabauza** [comment]
Yeah I think this is kind of a blocker, there will be planty more shortly, but we need to be able to login to our system first :)

**Comment by vatsalkul** [comment]
Sure @annabauza go ahead with this issue.

**Comment by annabauza** [comment]
I released it for anyone, @vatsalkul I have very limited time lately.

**Comment by vatsalkul** [comment]
No issue. I'll try to do it asap.

**Comment by jalajcodes** [comment]
I can work on it... I have plenty of experience with react and typescript

**Comment by annabauza** [comment]
Ahh OK so work on that first and I can u assign you from the other.

**Comment by jalajcodes** [comment]
> Ahh OK so work on that first and I can u assign you from the other. 

I didn't understand 😅

**Comment by annabauza** [comment]
Yes if license allow

**Comment by jalajcodes** [comment]
> Yes if license allow

most npm packages are open source so license shouldn't be a problem. Btw I just finished styling the login page, will start on making it work tomorrow.

**Comment by annabauza** [comment]
open source is great @jalajcodes

**Comment by annabauza** [comment]
@jalajcodes looking forward for that. Can we use Material UI library for that?

**Comment by jalajcodes** [comment]
@annabauza Okay!
