### ISSUE TITLE
docs: Create Code of Conduct markdown file

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/stem-diverse-tv-cms#13]
## Description
As a developer,
I need to see Code of Conduct for the repository
## Acceptance Criteria
File path  `./github/CODE_OF_CONDUCT.md`
## Update [Required]
 

- [ ] Create CODE_OF_CONDUCT.md - Reference: https://github.com/anitab-org/mentorship-android/blob/develop/.github/CODE_OF_CONDUCT.md

## Definition of Done

- [ ] All of the required items are completed.
- [ ] Approval by 2

## Estimation
2 hour

**Comment by annabauza** [comment]
approved

**Comment by harsh1206** [comment]
can i work on this issue ?

**Comment by annabauza** [comment]
yours @harsh1206
