### ISSUE TITLE
docs: Create Reporting Guidelines markdown file

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/stem-diverse-tv-cms#14]
## Description
As a developer,
I need to see Reporting Guidelines for the repository
## Acceptance Criteria
File path  `./github/REPORTING_GUIDELINES.md`
## Update [Required]

- [ ] Create REPORTING_GUIDELINES.md - Reference: https://github.com/anitab-org/mentorship-android/blob/develop/.github/REPORTING_GUIDELINES.md
## Definition of Done

- [ ] All of the required items are completed.
- [ ] Approval by 2

## Estimation
1 hour

**Comment by Rahulm2310** [comment]
If approved, I would like to take up this issue.

**Comment by annabauza** [comment]
approved, @Rahulm2310 you already have first timer issue.

**Comment by Rahulm2310** [comment]
Yeah in the backend repo...not in this repo 🙂

**Comment by annabauza** [comment]
first time issue is per organisation if I remember correctly. @isabelcosta ?

**Comment by isabelcosta** [comment]
> first time issue is per organisation if I remember correctly.

yes it's a good opportunity for newcomers to introduce them to STEM Diverse TV @annabauza

**Comment by prachi237** [comment]
If it's open I would like to work on this issue

**Comment by annabauza** [comment]
yours @prachi237
