### ISSUE TITLE
Bug: Clicking on logo goes to incorrect link

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/stem-diverse-tv-cms#22]
### Describe the bug

Clicking on the logo goes to https://anitab-org.github.io/ whereas it should go to https://anitab-org.github.io/stem-diverse-tv-cms/ .After that when we refresh, [AnitaB.org open source.](https://anitab-org.github.io/) website shows up.

### To Reproduce
1. Go to https://anitab-org.github.io/stem-diverse-tv-cms/
2. Click on logo
3. Refresh the page

### Expected behavior

Logo should be linked to https://anitab-org.github.io/stem-diverse-tv-cms/

### Screenshots

![stem-cms-issue](https://user-images.githubusercontent.com/54268438/107252628-8b813100-6a5b-11eb-939e-aac4ac162f12.gif)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@annabauza Can you please confirm/approve this issue. If yes, I would like to work on this. Thanks 🙂

**Comment by annabauza** [comment]
Approved

**Comment by Rahulm2310** [comment]
@annabauza  Can I be assigned

**Comment by annabauza** [comment]
Yours @Rahulm2310
