### ISSUE TITLE
Add Stem Diverse logo in title bar 

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/stem-diverse-tv-cms#25]
### Describe the bug

Stem diverse cms doesn't have logo in the title bar .

### Expected behavior

Stem diverse Icon Logo should be added in the title bar.

### Screenshots

![Screenshot from 2021-02-09 23-06-31](https://user-images.githubusercontent.com/44670961/107403778-8ab7d000-6b2b-11eb-8ecf-32cc4bfebed7.png)

### Desktop (please complete the following information):
 - OS: Ubuntu 20.04
 - Browser : Firefox

**Comment by chinmaym07** [comment]
Please label it as a first timer issue. @annabauza

**Comment by annabauza** [comment]
can't see this issue on https://anitab-org.github.io/stem-diverse-tv-cms/
