### ISSUE TITLE
Bug: Add technical stack and setup and run instructions, branches in readme

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/stem-diverse-tv-cms#26]
### Describe the bug

As this project is now actively developed, we should add technical stack and setup instructions in readme

### To Reproduce
1. Go to https://github.com/anitab-org/stem-diverse-tv-cms
2. Scroll down to readme.md

### Expected behavior

Technical stack and setup instructions should be added in readme.md

### Screenshots

![stem](https://user-images.githubusercontent.com/54268438/107404523-61e40a80-6b2c-11eb-9440-91c7420d6e6d.JPG)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@annabauza Can you please confirm/approve this issue. Thanks 🙂

**Comment by annabauza** [comment]
Yes @Rahulm2310

**Comment by Rahulm2310** [comment]
@annabauza Can I be assigned this

**Comment by annabauza** [comment]
yours @Rahulm2310
