### ISSUE TITLE
Registration does not work

### ISSUE THREAD

**Issue by annabauza** [anitab-org/stem-diverse-tv-cms#27]
### Describe the bug
Registration form does not do anything.

### To Reproduce
Steps to reproduce the behaviour:
1. Go to https://anitab-org.github.io/
2. Click on Register
3. Fill registration form properly and click on Register button at the bottom of the form
4. See error registration does not work

### Expected behaviour
Should register user and show link to click

### Screenshots
![Screenshot 2021-02-11 at 21 02 13](https://user-images.githubusercontent.com/31966073/107698437-73542080-6cac-11eb-9b66-76f0c6d828e1.png)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

### Smartphone (please complete the following information):
 - Device: Any
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Aryaman19** [comment]
Can I take this issue?

**Comment by annabauza** [comment]
@Aryaman19 yours

**Comment by chinmaym07** [comment]
@annabauza Can you please let me know what error do you get while registering .?

**Comment by annabauza** [comment]
Yes can you test it and rise an issue if it occur for login as well?

**Comment by Aryaman19** [comment]
I have made the required changes but I cannot test those because of cors policy. Has cors been added in backend??
![Screenshot (355)](https://user-images.githubusercontent.com/46364632/108158561-2ee0de80-710b-11eb-978c-25eda2ad523a.png)

**Comment by Aryaman19** [comment]
But when I have disabled cors policy in the browser , I am able to register successfully.  
![Screenshot (356)](https://user-images.githubusercontent.com/46364632/108159959-1e7e3300-710e-11eb-92e9-1c02890939fd.png)

**Comment by Aryaman19** [comment]
Should I create a Pull Request then?? @annabauza 
But even if we merge the changes , in normal browsers register will not work untill we enable cors in the backend.

**Comment by annabauza** [comment]
please create backend issue for that. If you have fix please create feel free to create PR.
