### ISSUE TITLE
Bug: Regiteration & Login Does not work on the hosted App

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/stem-diverse-tv-cms#29]
### Describe the bug

A user is unable to login on the hosted website as the requests are directed to wrong API (https://anitab-org.github.io/users/login). I have registered a test user on Backend hosted on Heroku & verified the user & when I try to login with that user it shows error like 'please check your password & username '.

### Expected behavior

All the requests coming from the Frontend should be directed to Backend hosted on Heroku & the login section should show the correct error that is coming from the Backend while registering or while logging in to the application. This type of error message when a user has entered correct credentials ,will effect User experience badly.

### Screenshots

![Peek 2021-02-12 21-03](https://user-images.githubusercontent.com/44670961/107788427-64d23b80-6d76-11eb-85da-3a754da8eab9.gif)
![Screenshot from 2021-02-12 21-06-45](https://user-images.githubusercontent.com/44670961/107788371-5552f280-6d76-11eb-9d93-b05396043025.png)
![Peek 2021-02-12 21-04](https://user-images.githubusercontent.com/44670961/107794816-eb3e4b80-6d7d-11eb-880d-4dd93da670af.gif)
### Desktop (please complete the following information):
 - OS: Ubuntu 20.04
 - Browser Firefox

### Additional Context

**Comment by jalajcodes** [comment]
Are you going to work on it or can I?

**Comment by chinmaym07** [comment]
@jalajcodes If possible Can I do this  .?

**Comment by jalajcodes** [comment]
> @jalajcodes If possible Can I do this  

Sure go ahead! 😉

**Comment by jalajcodes** [comment]
@chinmaym07 please update us on your progress? It's a blocker for the cms.

Also, can you change the issue title to also include registration as it also has the same problem.

**Comment by chinmaym07** [comment]
@jalajcodes  sorry for the delay as my exams are going on ..will try to complete this today.
