### ISSUE TITLE
Welcome unknown user when first visiting website

### ISSUE THREAD

**Issue by ayan-biswas0412** [anitab-org/stem-diverse-tv-cms#33]
### Describe the bug
When I first opens the website it shows welcome unknown user 

### To Reproduce
First run the project locally as per the instruction in readme
1. Go to http://localhost:3000

### Expected behavior
There should be a common welcome page and after login it should return the message Welcome user_name.
For this I think we have to return two separate type of components based on ```auth.authState```

### Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52851184/107874091-1d19f400-6edd-11eb-8adb-291e0bced479.png">

### Desktop (please complete the following information):
 - OS: macOS Big Sur
 - Browser [safari]
 - Version [11.1]

### Smartphone (please complete the following information):
 - Device: [Samsung Galaxy A 50]
 - OS: [Android Marshmallow]
 - Browser [chrome]

### Additional context
NA

**Comment by annabauza** [comment]
can you specify the content @ayan-biswas0412 ?

**Comment by ayan-biswas0412** [comment]
> can you specify the content @ayan-biswas0412 ?

Yah like we can give e coming soon page or just normal welcome to our stem diverse TV CMS like this we can show

**Comment by annabauza** [comment]
closing, duplicate #28
