### ISSUE TITLE
Feat: Deploying the project on heroku or netlify. 

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/stem-diverse-tv-cms#34]
### Is your feature request related to a problem? Please describe.

As gh-pages is already occupied by anitab-org.github.io website, we sometimes get incorrect/conflicting routes in this project. 
For example: /login route when refreshed throws error. Although, it is completely normal gh-pages behavior as it looks for a repository named `login'. Similar issue is faced with register route.
![stem-cms-issue-heroku](https://user-images.githubusercontent.com/54268438/108106966-a0417280-70b4-11eb-9a63-9ecda327d28b.gif)

### Describe the solution you'd like

As now the project is in active development, we should deploy the project to some free hosting providers like [Heroku](https://www.heroku.com/) or [Netlify](https://www.netlify.com/). 

### Describe alternatives you've considered

1. [Heroku](https://www.heroku.com/)
2. [Netlify](https://www.netlify.com/)

**Comment by Rahulm2310** [comment]
@annabauza Please share your views. 🙂

**Comment by annabauza** [comment]
@Rahulm2310 are you paying for heroku? Rather then that I would suggest to keep stem-diverse-tv-cms as root in package.json :)

**Comment by Rahulm2310** [comment]
> I would suggest to keep stem-diverse-tv-cms as root in package.json :)

@annabauza We can surely do that. But wouldn't it be better to have custom hosting with free providers like netlify or heroku. I think it would be a much robust solution.

**Comment by annabauza** [comment]
Those free hosting providers have limits and we already used them all. We plan this things very carefully with admins, because at some point we need to scale up and those calculations need to be taken under consideration. We know. it's easier, quicker and yare yare, but we trying to do our work here smart, rather than lazy and costly.

**Comment by Rahulm2310** [comment]
@annabauza Got your point 👍 . Should I create seperate issue to add stem-diverse-tv-cms as root in package.json or edit this issue description ?

**Comment by annabauza** [comment]
please rise the bug that all links should be prefixes by https://anitab-org.github.io/stem-diverse-tv-cms/ so we should have https://anitab-org.github.io/stem-diverse-tv-cms/login instead of https://anitab-org.github.io/login etc.
