### ISSUE TITLE
No show password eye button in Login form

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/stem-diverse-tv-cms#35]
### Describe the bug

There is no show password eye button on Login form unlike we have in register form.

### To Reproduce
1. Go to http://localhost:3000/login
3.  See error

### Expected behavior

There should be a show/hide password toggle eye button

##### Login : 
![stem-login-form](https://user-images.githubusercontent.com/54268438/108404034-65227900-7245-11eb-8ab7-5af9080b297f.JPG)

##### Register : 
![image](https://user-images.githubusercontent.com/54268438/108404143-871bfb80-7245-11eb-9572-fa3bf34b3604.png)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@annabauza This can be a good `First Timers only` issue.

**Comment by annabauza** [comment]
approved

**Comment by guptag911** [comment]
@annabauza Can I work on this issue?

**Comment by annabauza** [comment]
@guptag911 yours
