### ISSUE TITLE
Bug: all links should be prefixed by /stem-diverse-tv-cms

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/stem-diverse-tv-cms#37]
### Describe the bug

As gh-pages is already occupied by anitab-org.github.io website, we sometimes get incorrect/conflicting routes in this project.
For example: /login route when refreshed throws error. Although, it is completely normal gh-pages behavior as it looks for a repository named `login'. Similar issue is faced with register route.

### To Reproduce
1. Go to https://anitab-org.github.io/stem-diverse-tv-cms/login
2. Refresh page

### Expected behavior

All links should be prefixed by `/stem-diverse-tv-cms` so we should have https://anitab-org.github.io/stem-diverse-tv-cms/login instead of https://anitab-org.github.io/login.

### Screenshots

![stem-cms-issue-heroku](https://user-images.githubusercontent.com/54268438/108106966-a0417280-70b4-11eb-9a63-9ecda327d28b.gif)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@annabauza I would like to fix this. 🙂

**Comment by Amulya-coder** [comment]
@Rahulm2310 this could be a good `first-timers` issue it is better if you give chance to other contributors to work on this :)
 
Cc: @annabauza

**Comment by annabauza** [comment]
@Amulya-coder I think it's actually quite tricky issue cause on top of that we want to investigate what breaks router links.

**Comment by Rahulm2310** [comment]
@annabauza Exactly. Can I be assigned this ?

**Comment by annabauza** [comment]
Yes your @Rahulm2310
