### ISSUE TITLE
[Feat]: Create config.yml for Welcome Bot

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/stem-diverse-tv-cms#42]
## Description
As a first time contributor,
I need a bot to help guide my first contribution,
so that I can follow this org's contribution guidelines.

## Mocks
![welcomebot](https://user-images.githubusercontent.com/54268438/109551979-40f15280-7af7-11eb-871a-2b04b03bb0a3.png)

## Acceptance Criteria
- [ ] newIssueWelcomeComment is complete with the correct links to this repo.
- [ ] newPRWelcomeComment is complete with the links to the project's stream or topic and the repo's Code of Conduct.
- [ ] firstPRMergeComment is complete.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Rahulm2310** [comment]
@annabauza Can you please add labels to this. 🙂

**Comment by nlok5923** [comment]
can i work on this issue if it is approved.

**Comment by annabauza** [comment]
@nlok5923 yours
