### ISSUE TITLE
clean: Remove .github/ISSUE_TEMPLATE folder

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/stem-diverse-tv-cms#46]
## Description
As a org contributor,
We need to maintain 1 version of issue templates used in the organization,
so that we can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. 

### Update [Required]
- [ ] [Remove .github/ISSUE_TEMPLATE]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Anmollenka** [comment]
I would like to work on this issue.

**Comment by Amulya-coder** [comment]
@Anmollenka as you have been already assigned to #58 so I can't assign you this issue after creating a successful pr you can claim it again then I will assign it to you  :)

**Comment by Aryamanz29** [comment]
@Amulya-coder I want to work on this issue

**Comment by Amulya-coder** [comment]
Your's @Aryamanz29  :)
