### ISSUE TITLE
Bug: Update README.md

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/stem-diverse-tv-cms#5]
## Describe the Bug

It is written here that this is the backend of the project . 

![Screenshot_2021-01-28 anitab-org stem-diverse-tv-cms](https://user-images.githubusercontent.com/44670961/106166677-70d4cf80-61b2-11eb-9c56-9851b0a1f61c.png)

There is written get into anitab.org.github.io directory.

![Screenshot_2021-01-29 anitab-org stem-diverse-tv-cms](https://user-images.githubusercontent.com/44670961/106243036-a4553f80-622e-11eb-9548-6c57ea288a39.png)

## Desktop (please complete the following information):
- OS: Ubuntu 20.04
- Browser : Firefox

**Comment by annabauza** [comment]
approved @chinmaym07

**Comment by chinmaym07** [comment]
@annabauza  Please label it as first timer issue ...as it can serve as a starting point for anyone wanting to contribute to this project. !

**Comment by Amulya-coder** [comment]
Hi, I would like to work on this, Can I please be assigned.

**Comment by annabauza** [comment]
@Amulya-coder yours
