### ISSUE TITLE
Bug: Add some margin on navbar and temporary content

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/stem-diverse-tv-cms#53]
### Describe the bug

Less margin between the navbar and content in temporary homepage
### To Reproduce
1. Go to Homepage
2. See error

### Expected behavior

Add some margin/padding between the content and navbar. 
### Screenshots

![image](https://user-images.githubusercontent.com/66299533/112124591-854cab80-8be8-11eb-86b3-f257d858297e.png)

### Desktop (please complete the following information):
 - OS: Ubuntu 20.04
 - Browser Firefox web browser
 - Version --

### Additional context

The page is temporary until the landing page is ready so everything including the temporary content will be removed

**Comment by Rahulm2310** [comment]
@Aaishpra as you already know, this is just temporary and will be removed as soon as the design for the home page is ready. I don't think there is need for this as the project is not in production. We can let it be as it is and wait for the designs.

**Comment by devkapilbansal** [comment]
Closing as this is not needed
