### ISSUE TITLE
Setup black formatter

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/stem-diverse-tv-cms#54]
### Is your feature request related to a problem? Please describe.

As a developer, I need to have good, structured, readable code to be able to read through it painlessly and effortlessly.

### Describe the solution you'd like

The idea is to run Black through a single pass, Add workflow to ensure code is formatted before it is merged to main codebase.

### Additional context

Black formatter is included in [anitab-forms-backend](https://github.com/anitab-org/anitab-forms-backend/blob/develop/.github/workflows/qa-checks.yml)

**Comment by jalajcodes** [comment]
Umm... you're aware this project uses javascript not python, ryt?

**Comment by Amulya-coder** [comment]
Ohh!😣 sorry @jalajcodes I forget about this project uses javascript only.
