### ISSUE TITLE
Add code linter and formatter to enhance code quality and maintain consistency

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/stem-diverse-tv-cms#55]
### Is your feature request related to a problem? Please describe.

It is necessary for a project to have clear consistent coding conventions. Besides that linting is also very helpful for finding certain classes of bugs and fixing them before runtime.

### Describe the solution you'd like

[Eslint](https://eslint.org/) and [Prettier](https://prettier.io/) is the most popular code linter and formatter for <b>Javascript</b>.
- Integrate Eslint into the project
- Integrate Prettier into the project
- Make Eslint work with prettier i.e. Eslint for linting and Prettier for formatting code
- Add a brief description about them in the project readme.
- Add Github workflows to ensure the guidelines are followed by every contributor.

### Additional context

This is also used in [anitab-forms-web](https://github.com/anitab-org/anitab-forms-web/blob/develop/.github/workflows/qa-checks.yml) you can take reference from that.

**Comment by Amulya-coder** [comment]
@annabauza can you please approve this issue.

**Comment by Aryamanz29** [comment]
@Amulya-coder  I would like to work on this

**Comment by Amulya-coder** [comment]
@Aryamanz29 Please go ahead
