### ISSUE TITLE
Docs: Remove table of contents from the readme.md

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/stem-diverse-tv-cms#58]
### Describe the bug
As now with the GitHub UI, we have a dropdown list for table of contents, we don't need a manual table of contents anymore.

### Expected behavior
Remove the manually added table of contents from the readme.md

### Screenshots
![image](https://user-images.githubusercontent.com/54268438/112667177-f7d8b800-8e82-11eb-8fbe-92a81c0c4fab.png)

![image](https://user-images.githubusercontent.com/54268438/112667236-07f09780-8e83-11eb-920c-db69b4f0ae3e.png)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Anmollenka** [comment]
I would like to work on this issue.

**Comment by Rahulm2310** [comment]
Yours @Anmollenka ☺️. Happy documenting.

**Comment by Amulya-coder** [comment]
@Anmollenka can you please give the Updates!! .

**Comment by Anmollenka** [comment]
Would raise a pr by tomorrow
