### ISSUE TITLE
UI: Add the badge in Readme.md

### ISSUE THREAD

**Issue by khushishikhu** [anitab-org/stem-diverse-tv-cms#59]
### Is your feature request related to a problem? Please describe.

I would like if we can have the badges of Tech Stack in the Readme.md . 

##Badges
Badges can be for reactjs , html and other tech-stack used in this project

**Comment by Rahulm2310** [comment]
@khushishikhu Can you please be more descriptive. The issue looks vague.

**Comment by nandini45** [comment]
@khushishikhu  can you update the work as Rahul said

**Comment by khushishikhu** [comment]
@Rahulm2310 I have updated the issue description. I guess it looks right now

**Comment by annabauza** [comment]
I don't think it's a UI task, you don't design those badges, no?

**Comment by khushishikhu** [comment]
@annabauza yes you are right , we do not design those badges but those are similar to those which are already in the Readme (like zulip chat and open source badge). But those are available on the internet which can be added easily by which Readme will look more good

**Comment by annabauza** [comment]
@khushishikhu can you remove the ui label please?

**Comment by khushishikhu** [comment]
> @khushishikhu can you remove the ui label please?

yes sure

**Comment by HeroicHitesh** [comment]
@khushishikhu We have labels in the About section for this purpose, I think instead of adding badges in README.md for tech-stacks we can add labels in the About section of the repo that will also help this repository to show up in GitHub Search using labels
cc @annabauza

**Comment by devkapilbansal** [comment]
@HeroicHitesh labels are added in about section to make the repository searchable but in README file for the users to know more about the project.

**Comment by jaivanti** [comment]
Hi, I have pulled a request to add react, html, css, typescript badges in readme.md file. Do have a look!
Cheers!

**Comment by Rahulm2310** [comment]
@jaivanti if you want to work on this issue then you need to comment here requesting a maintainer to assign you. Once you are assigned, only then submit a PR. Good Luck 😊

**Comment by jaivanti** [comment]
Oh! Sorry for that. I will do follow it from next time

**Comment by jaivanti** [comment]
@khushishikhu Can you please assign me and check my pull request too. Sorry! I didn't know that we had to first get assigned
