### ISSUE TITLE
fix: Incorrect stars and forks in README badge

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/stem-diverse-tv-cms#65]
### Describe the bug

The stars and forks count displayed in README.md file is inconsistent with the actual numbers.

### To Reproduce
1. Go to [main page of this repo](https://github.com/anitab-org/stem-diverse-tv-cms)
2. See Inconsistency with number of stars and fork count

### Estimated Time
0.5 hrs

**Comment by keshavgbpecdelhi** [comment]
Hi, I am a beginner. Could you pls assign this to me?

**Comment by keshavgbpecdelhi** [comment]
Thankyou Sir

Do we have to change this 33 and 68 to 3 and 18?

![20210415_205731](https://user-images.githubusercontent.com/56075233/114895750-616a3780-9e2d-11eb-9085-2762c26d3dd2.jpg)

And can you pls share the reference how to do it. (If possible)

**Comment by Aryamanz29** [comment]
> Thankyou Sir
> 
> Do we have to change this 33 and 68 to 18 and 3?
> 
> ![20210415_205731](https://user-images.githubusercontent.com/56075233/114895750-616a3780-9e2d-11eb-9085-2762c26d3dd2.jpg)
> 
> And can you pls share the reference how to do it. (If possible)

Yeah, you got this right just open `README.md` and figure out where this link points to. I think it's using `shields.io` behind the scenes and you need to change that links only.

For ref: https://shields.io/category/social

**Comment by keshavgbpecdelhi** [comment]
Thanks for the explaination and the reference. Now understood🙏
