### ISSUE TITLE
docs: Create Contribution guidelines markdown file

### ISSUE THREAD

**Issue by annabauza** [anitab-org/stem-diverse-tv-cms#7]
## Description
As a developer,
I need to see contribution guidelines,
so that I can contribute.

## Acceptance Criteria
File path `./github/CONTRIBUTE.md`

### Update [Required]
- [ ] Create CONTRIBUTING.md - Reference: https://github.com/anitab-org/mentorship-android/blob/develop/.github/CONTRIBUTING.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2

## Estimation
1 hour

**Comment by NenadPantelic** [comment]
@annabauza  I would take this one.

**Comment by annabauza** [comment]
yours @NenadPantelic

**Comment by NenadPantelic** [comment]
@annabauza  If I think about this more in-depth, probably this is a good `First-timers` issue :thinking:. What do you think?

**Comment by annabauza** [comment]
Yes good call

**Comment by Aryaman19** [comment]
Can I work on this issue?

**Comment by annabauza** [comment]
yes @Aryaman19 yours

**Comment by shades-7** [comment]
hey, can I work on this?

**Comment by annabauza** [comment]
yes @shades-7 yours :)

**Comment by annabauza** [comment]
sorry @shades-7 , @Aryaman19 is already assigned to this issue.

**Comment by Aryaman19** [comment]
@annabauza I have solved the issue, created the pull request and you have already merged it 2-3 days ago.

**Comment by annabauza** [comment]
@Aryaman19 I think you haven't link the issue in the pr properly, otherwise issue would closed itself.
