### ISSUE TITLE
docs: Create Issue Templates

### ISSUE THREAD

**Issue by annabauza** [anitab-org/stem-diverse-tv-cms#8]
## Describe the bug/feature
As a developer, 
I need to see the issue templates preloaded on clicking new issue,
so that I can use those templates to create issues. 

### Update [Required]
Created Issue Templates for
- [ ] User Story
- [ ] New Feature
- [ ] Bug Report
Reference: https://github.com/anitab-org/anitab-org.github.io/tree/develop/.github/ISSUE_TEMPLATE

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Expected behavior
- [ ] On creating a new issue, the issue template should get preloaded.

## Estimation
1 hour

**Comment by Aaishpra** [comment]
@annabauza can I take this up?

**Comment by annabauza** [comment]
sure @Aaishpra , yours
