### ISSUE TITLE
feat: Create register form so user could register to our backend

### ISSUE THREAD

**Issue by annabauza** [anitab-org/stem-diverse-tv-cms#9]
### Is your feature request related to a problem? Please describe.
As a user I want to fill register form  so I could create an account on our [backend](https://stem-diverse-tv.herokuapp.com/).

### Describe the solution you'd like
Registration form design can be find [here](https://www.figma.com/file/klxnTZJ8Z2uAtxHS1CRTWO/Untitled?node-id=1%3A10)
![Desktop - 1 (2)](https://user-images.githubusercontent.com/31966073/106380127-25841200-63a8-11eb-8923-a9734de1e91a.png)

### Describe alternatives you've considered
Maybe checking password (repeat password) should be done here.

### Additional context
At the moment there is no email confirmation so we can just display a link to click on webside for now.
For designs `outlined text fields` has been used from [Material.io](https://material.io/components/text-fields#usage)

**Comment by chinmaym07** [comment]
@annabauza  I have completed issue #6  .If possible Can I try to work upon this.

**Comment by annabauza** [comment]
@chinmaym07 yours!

**Comment by annabauza** [comment]
how it's going @chinmaym07 ?

**Comment by chinmaym07** [comment]
Yes working on it .I will try to send a pr asap.  👍🏻 😀 @annabauza

**Comment by annabauza** [comment]
great thanks!

**Comment by annabauza** [comment]
@chinmaym07 we have [login](https://anitab-org.github.io/login) can you follow [this PR](https://github.com/anitab-org/stem-diverse-tv-cms/pull/18) for register to keep consistancy?

**Comment by chinmaym07** [comment]
Yes @annabauza.I have completed this issue only some validation checks work is left & I am working on that . Will make a pr asap. Sorry for the delay .

**Comment by annabauza** [comment]
Great looking forward for that!

**Comment by chinmaym07** [comment]
![Peek 2021-02-09 02-48](https://user-images.githubusercontent.com/44670961/107282925-b1213100-6a81-11eb-953f-3a45c3cde359.gif)
@annabauza  .Please check this .

**Comment by chinmaym07** [comment]
Shall I add the logo of stem diverse-cms in as an icon in tab .? @annabauza 
![Screenshot from 2021-02-09 13-27-43](https://user-images.githubusercontent.com/44670961/107332785-a050d980-6ada-11eb-9096-d5d5345494e2.png)

**Comment by annabauza** [comment]
Logo can be added. Reset password is not supported on backend. Multiple accounts is issue for backend.

**Comment by annabauza** [comment]
Reopening because register does not work on github static pages

**Comment by annabauza** [comment]
closing there is separate issue for that
